
services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: pos_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT=/app/app/secrets/firebase-service-account.json
    volumes:
      - ./app:/app/app
      - ~/firebase-secrets/firebase-service-account.json:/app/app/secrets/firebase-service-account.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload